#!/usr/bin/env node
"use strict";
/* ══════════════════════════════════════════════════════════════
   VERIFY-PROOF — standalone audit-bundle verifier
   ──────────────────────────────────────────────────────────────
   For a merchant's finance team, an external auditor, or a Razorpay
   judge: download the Audit Seal bundle from the console (Audit
   tab → "Export audit seal"), then run:

       node verify-proof.js axiom-audit-bundle.json

   The script recomputes EVERYTHING from the bundle's own bytes:
     1. every entry's chain hash — sha256(seq|ts|prev_hash|kind|canonical payload)
     2. every prev_hash link — one cut anywhere is reported exactly
     3. the merkle root over all entry hashes

   It imports NOTHING from the engine (not even audit.js) — the
   verification logic is self-contained so that the bundle and this
   file can be handed to a third party together, and there is no
   possibility of the engine's own code being the thing that
   vouches for itself. Zero dependencies, Node >= 16.

   Exit code 0 = valid, 1 = tampered/malformed, 2 = usage error.
   ══════════════════════════════════════════════════════════════ */

const crypto = require("crypto");
const fs = require("fs");

const sha256 = (s) => crypto.createHash("sha256").update(s).digest("hex");
const GENESIS = "0".repeat(64);

function canonical(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";
  const keys = Object.keys(value).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + canonical(value[k])).join(",") + "}";
}

function merkleRoot(entryHashes) {
  if (!entryHashes.length) return GENESIS;
  let level = entryHashes.map((h) => sha256(`axiom-leaf:${h}`));
  while (level.length > 1) {
    if (level.length % 2 === 1) level.push(level[level.length - 1]);
    const next = [];
    for (let i = 0; i < level.length; i += 2) next.push(sha256(`axiom-node:${level[i]}${level[i + 1]}`));
    level = next;
  }
  return level[0];
}

function fail(msg) {
  console.error(`\n  ✗ VERIFICATION FAILED — ${msg}`);
  console.error("    The bundle does not match its own hashes. Either the file was\n    edited after export, or it was generated by something else.\n");
  process.exit(1);
}

function main() {
  const file = process.argv[2];
  if (!file) {
    console.error("usage: node verify-proof.js <audit-bundle.json>");
    process.exit(2);
  }
  let bundle;
  try {
    bundle = JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (e) {
    console.error(`usage: node verify-proof.js <audit-bundle.json>  (could not read/parse ${file}: ${e.message})`);
    process.exit(2);
  }

  const entries = bundle.entries;
  if (!Array.isArray(entries) || entries.length === 0) fail("bundle has no entries");

  /* The one schema-aware step, documented: the engine's decision
     payloads carry `dual_control_approved: approvedHere || undefined`
     (recover2.js). JSON drops undefined-valued keys on export, so the
     verifier re-inserts the key before hashing to reproduce the
     engine's exact canonical bytes. No other payload field in any
     entry kind is ever undefined — verified by test/enterprise.test.js
     and by the engine's own 146-test suite. */
  for (const e of entries) {
    if (e.kind === "decision" && e.payload && !("dual_control_approved" in e.payload)) {
      e.payload.dual_control_approved = undefined;
    }
  }

  console.log(`\n  AXIOM RECOVER — audit seal verification`);
  console.log(`  ${"─".repeat(52)}`);
  console.log(`  bundle          ${file}`);
  console.log(`  exported        ${bundle.exported_at ?? "?"}`);
  console.log(`  run             ${bundle.run_id ?? "?"} (seed ${bundle.seed ?? "?"})`);
  console.log(`  entries         ${entries.length}`);

  /* 1 — per-entry hash + 2 — chain links */
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    if (e.seq !== i) fail(`entry ${i} carries seq ${e.seq} — inserted, removed or reordered`);
    const expectedPrev = i === 0 ? GENESIS : entries[i - 1].hash;
    if (e.prev_hash !== expectedPrev) fail(`entry ${i}: prev_hash does not match entry ${i - 1}'s hash — chain cut here`);
    const recomputed = sha256(`${e.seq}|${e.ts}|${e.prev_hash}|${e.kind}|${canonical(e.payload)}`);
    if (recomputed !== e.hash) fail(`entry ${i}: stored hash does not match its own contents — modified after writing`);
  }
  console.log(`  chain           intact (every hash + every link recomputed)`);

  /* 3 — merkle root */
  const root = merkleRoot(entries.map((e) => e.hash));
  if (root !== bundle.merkle_root) fail(`merkle root mismatch: bundle says ${bundle.merkle_root?.slice(0, 16)}…, recomputation says ${root.slice(0, 16)}…`);
  console.log(`  merkle root     ${root.slice(0, 32)}…`);
  console.log(`                  ✔ matches the bundle's committed root`);

  /* prevented-actions tally, cross-checked from payload traces */
  const blocked = entries.reduce((n, e) => n + ((e.payload?.trace || []).filter((t) => t.result === "block").length), 0);
  console.log(`  gate vetoes     ${blocked} recorded inside the payloads`);

  console.log(`\n  ✓ VALID — no entry in this bundle was added, removed, edited or\n    reordered after export, and the committed merkle root reproduces.\n`);
}

main();
